<?php

namespace Container7ubHwfY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H64Kpxq.App\Controller\EventController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H64Kpxq.App\\Controller\\EventController::delete()'] = ($container->privates['.service_locator.H64Kpxq'] ?? $container->load('get_ServiceLocator_H64KpxqService'))->withContext('App\\Controller\\EventController::delete()', $container);
    }
}
