<?php

namespace ContainerA9Cn853;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieEventControllermodifierCategorieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j2FHMHc.App\Controller\CategorieEventController::modifierCategorie()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j2FHMHc.App\\Controller\\CategorieEventController::modifierCategorie()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.j2FHMHc.App\\Entity\\CategorieEvent', NULL, 'Cannot autowire service ".service_locator.j2FHMHc": it needs an instance of "App\\Entity\\CategorieEvent" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'categorie' => 'App\\Entity\\CategorieEvent',
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\CategorieEventController::modifierCategorie()', $container);
    }
}
