<?php

namespace ContainerA9Cn853;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uOCv2n7.App\Controller\EventController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uOCv2n7.App\\Controller\\EventController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.uOCv2n7.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.uOCv2n7": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
        ], [
            'event' => 'App\\Entity\\Event',
        ]))->withContext('App\\Controller\\EventController::show()', $container);
    }
}
