framework:
    messenger:
        default_bus: messenger.bus.default
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 1000  # Vérifie la base toutes les 1 sec
                retry_strategy:
                    max_retries: 3
                    delay: 1000               # 1 sec avant le premier retry
                    multiplier: 2            # double à chaque échec
                    max_delay: 10000         # max 10 sec d'attente

            failed: 'doctrine://default?queue_name=failed'

        buses:
            messenger.bus.default: ~

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
