<?php

namespace ContainerBLIV09x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieEventControllerajouterCategorieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zuLlZtR.App\Controller\CategorieEventController::ajouterCategorie()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zuLlZtR.App\\Controller\\CategorieEventController::ajouterCategorie()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\CategorieEventController::ajouterCategorie()', $container);
    }
}
