<?php

namespace ContainerV9y3Syx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieEventControllerlisteCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LnTf_q..App\Controller\CategorieEventController::listeCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LnTf_q..App\\Controller\\CategorieEventController::listeCategories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\CategorieEventRepository', 'getCategorieEventRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\CategorieEventRepository',
        ]))->withContext('App\\Controller\\CategorieEventController::listeCategories()', $container);
    }
}
