<?php

namespace ContainerCoD3rDl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NinPwK2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NinPwK2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NinPwK2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategorieEventController::ajouterCategorie' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\CategorieEventController::ajouterCategorie()', 'getCategorieEventControllerajouterCategorieService', true],
            'App\\Controller\\CategorieEventController::listeCategories' => ['privates', '.service_locator.LnTf_q..App\\Controller\\CategorieEventController::listeCategories()', 'getCategorieEventControllerlisteCategoriesService', true],
            'App\\Controller\\CategorieEventController::supprimerCategorie' => ['privates', '.service_locator.csPTnRl.App\\Controller\\CategorieEventController::supprimerCategorie()', 'getCategorieEventControllersupprimerCategorieService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategorieEventController:ajouterCategorie' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\CategorieEventController::ajouterCategorie()', 'getCategorieEventControllerajouterCategorieService', true],
            'App\\Controller\\CategorieEventController:listeCategories' => ['privates', '.service_locator.LnTf_q..App\\Controller\\CategorieEventController::listeCategories()', 'getCategorieEventControllerlisteCategoriesService', true],
            'App\\Controller\\CategorieEventController:supprimerCategorie' => ['privates', '.service_locator.csPTnRl.App\\Controller\\CategorieEventController::supprimerCategorie()', 'getCategorieEventControllersupprimerCategorieService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategorieEventController::ajouterCategorie' => '?',
            'App\\Controller\\CategorieEventController::listeCategories' => '?',
            'App\\Controller\\CategorieEventController::supprimerCategorie' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategorieEventController:ajouterCategorie' => '?',
            'App\\Controller\\CategorieEventController:listeCategories' => '?',
            'App\\Controller\\CategorieEventController:supprimerCategorie' => '?',
        ]);
    }
}
