<?php

namespace ContainerXHziWt7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_As7235eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.As7235e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.As7235e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategorieEventController::ajouterCategorie' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\CategorieEventController::ajouterCategorie()', 'getCategorieEventControllerajouterCategorieService', true],
            'App\\Controller\\CategorieEventController::listeCategories' => ['privates', '.service_locator.LnTf_q..App\\Controller\\CategorieEventController::listeCategories()', 'getCategorieEventControllerlisteCategoriesService', true],
            'App\\Controller\\CategorieEventController::supprimerCategorie' => ['privates', '.service_locator.csPTnRl.App\\Controller\\CategorieEventController::supprimerCategorie()', 'getCategorieEventControllersupprimerCategorieService', true],
            'App\\Controller\\CategorieEventController::modifierCategorie' => ['privates', '.service_locator.j2FHMHc.App\\Controller\\CategorieEventController::modifierCategorie()', 'getCategorieEventControllermodifierCategorieService', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.wxPd78M.App\\Controller\\EventController::index()', 'getEventControllerindexService', true],
            'App\\Controller\\EventController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\EventController::new()', 'getEventControllernewService', true],
            'App\\Controller\\EventController::show' => ['privates', '.service_locator.uOCv2n7.App\\Controller\\EventController::show()', 'getEventControllershowService', true],
            'App\\Controller\\EventController::edit' => ['privates', '.service_locator.H64Kpxq.App\\Controller\\EventController::edit()', 'getEventControllereditService', true],
            'App\\Controller\\EventController::delete' => ['privates', '.service_locator.H64Kpxq.App\\Controller\\EventController::delete()', 'getEventControllerdeleteService', true],
            'App\\Controller\\EventController::list' => ['privates', '.service_locator.wxPd78M.App\\Controller\\EventController::list()', 'getEventControllerlistService', true],
            'App\\Controller\\EventController::showevent' => ['privates', '.service_locator.uOCv2n7.App\\Controller\\EventController::showevent()', 'getEventControllershoweventService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategorieEventController:ajouterCategorie' => ['privates', '.service_locator.zuLlZtR.App\\Controller\\CategorieEventController::ajouterCategorie()', 'getCategorieEventControllerajouterCategorieService', true],
            'App\\Controller\\CategorieEventController:listeCategories' => ['privates', '.service_locator.LnTf_q..App\\Controller\\CategorieEventController::listeCategories()', 'getCategorieEventControllerlisteCategoriesService', true],
            'App\\Controller\\CategorieEventController:supprimerCategorie' => ['privates', '.service_locator.csPTnRl.App\\Controller\\CategorieEventController::supprimerCategorie()', 'getCategorieEventControllersupprimerCategorieService', true],
            'App\\Controller\\CategorieEventController:modifierCategorie' => ['privates', '.service_locator.j2FHMHc.App\\Controller\\CategorieEventController::modifierCategorie()', 'getCategorieEventControllermodifierCategorieService', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.wxPd78M.App\\Controller\\EventController::index()', 'getEventControllerindexService', true],
            'App\\Controller\\EventController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\EventController::new()', 'getEventControllernewService', true],
            'App\\Controller\\EventController:show' => ['privates', '.service_locator.uOCv2n7.App\\Controller\\EventController::show()', 'getEventControllershowService', true],
            'App\\Controller\\EventController:edit' => ['privates', '.service_locator.H64Kpxq.App\\Controller\\EventController::edit()', 'getEventControllereditService', true],
            'App\\Controller\\EventController:delete' => ['privates', '.service_locator.H64Kpxq.App\\Controller\\EventController::delete()', 'getEventControllerdeleteService', true],
            'App\\Controller\\EventController:list' => ['privates', '.service_locator.wxPd78M.App\\Controller\\EventController::list()', 'getEventControllerlistService', true],
            'App\\Controller\\EventController:showevent' => ['privates', '.service_locator.uOCv2n7.App\\Controller\\EventController::showevent()', 'getEventControllershoweventService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategorieEventController::ajouterCategorie' => '?',
            'App\\Controller\\CategorieEventController::listeCategories' => '?',
            'App\\Controller\\CategorieEventController::supprimerCategorie' => '?',
            'App\\Controller\\CategorieEventController::modifierCategorie' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Controller\\EventController::new' => '?',
            'App\\Controller\\EventController::show' => '?',
            'App\\Controller\\EventController::edit' => '?',
            'App\\Controller\\EventController::delete' => '?',
            'App\\Controller\\EventController::list' => '?',
            'App\\Controller\\EventController::showevent' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategorieEventController:ajouterCategorie' => '?',
            'App\\Controller\\CategorieEventController:listeCategories' => '?',
            'App\\Controller\\CategorieEventController:supprimerCategorie' => '?',
            'App\\Controller\\CategorieEventController:modifierCategorie' => '?',
            'App\\Controller\\EventController:index' => '?',
            'App\\Controller\\EventController:new' => '?',
            'App\\Controller\\EventController:show' => '?',
            'App\\Controller\\EventController:edit' => '?',
            'App\\Controller\\EventController:delete' => '?',
            'App\\Controller\\EventController:list' => '?',
            'App\\Controller\\EventController:showevent' => '?',
        ]);
    }
}
