<?php

namespace ContainerXHziWt7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uOCv2n7.App\Controller\EventController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uOCv2n7.App\\Controller\\EventController::show()'] = ($container->privates['.service_locator.uOCv2n7'] ?? $container->load('get_ServiceLocator_UOCv2n7Service'))->withContext('App\\Controller\\EventController::show()', $container);
    }
}
