parameters:
  categorie_images_directory: "%kernel.project_dir%/public/uploads"
  pdf_directory: "%kernel.project_dir%/public/uploads/pdf"
  huggingface.api_token: '%env(HUGGINGFACE_API_TOKEN)%'
  postmark_api_key: '%env(POSTMARK_API_KEY)%'
  gemini_api_key: '%env(GEMINI_API_KEY)%'
  photos_directory: '%kernel.project_dir%/public/uploads/photos'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $client: "@http_client"

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      
  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]
    
  App\Form\:
    resource: "../src/Form"
    tags: ["controller.service_arguments"]

  App\Service\OffensiveSpeechDetector:
    arguments:
      $apiToken: '%huggingface.api_token%'

  App\Service\SmsService:
    arguments:
      $messageBirdApiKey: '%env(MESSAGEBIRD_API_KEY)%'
      $senderId: '%env(MESSAGEBIRD_SENDER_ID)%'

  App\Service\PostmarkService:
    arguments:
      $postmarkClient: '@Postmark\PostmarkClient'
      $fromEmail: '%env(POSTMARK_FROM_EMAIL)%'
      $logger: '@logger'

  Postmark\PostmarkClient:
    arguments:
      - '%env(POSTMARK_API_KEY)%'

  App\Service\MailService:
    arguments:
      $mailer: '@mailer.mailer'
      $logger: '@logger'

  App\Service\CalendarLinkGenerator: ~

  App\Service\ChatApiService:
    arguments:
      $geminiApiKey: '%gemini_api_key%'
