parameters:
  categorie_images_directory: "%kernel.project_dir%/public/uploads"
  pdf_directory: "%kernel.project_dir%/public/uploads/pdf"
  photos_directory: '%kernel.project_dir%/public/uploads/photos'
  gemini.api_key: '%env(GEMINI_API_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $client: "@http_client"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  App\Form\:
    resource: "../src/Form"
    tags: ["controller.service_arguments"]

  App\Service\ChatApiService:
    arguments:
      $geminiApiKey: '%gemini.api_key%'
