# services.yaml

# Paramètres de configuration (ajout de la clé API pour Postmark)
parameters:
    postmark_api_key: '%env(POSTMARK_API_KEY)%'

services:
    # Services par défaut
    _defaults:
        autowire: true      # Injection automatique des dépendances dans tes services
        autoconfigure: true # Enregistrement automatique des services en tant que commandes, abonnés aux événements, etc.

    # Services spécifiques
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Migrations,Tests,Kernel.php}'

    # Service SmsService
    App\Service\SmsService:
        arguments:
            $messageBirdApiKey: '%env(MESSAGEBIRD_API_KEY)%'
            $senderId: '%env(MESSAGEBIRD_SENDER_ID)%'

    # Service Postmark\Client (service pour l'envoi d'e-mails)
    App\Service\PostmarkService:
        arguments:
            $postmarkClient: '@Postmark\PostmarkClient'
            $fromEmail: '%env(POSTMARK_FROM_EMAIL)%'
            $logger: '@logger'

    Postmark\PostmarkClient:
        arguments:
            - '%env(POSTMARK_API_KEY)%'

    App\Service\MailService:
        arguments:
            $mailer: '@mailer.mailer'
            $logger: '@logger'

    App\Service\CalendarLinkGenerator: ~
