<?php

namespace ContainerBFIxJZ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.csPTnRl.App\Entity\CategorieEvent' shared service.
     *
     * @return \App\Entity\CategorieEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.csPTnRl": it needs an instance of "App\\Entity\\CategorieEvent" but this type has been excluded in "config/services.yaml".');
    }
}
