<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP3gS4p1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP3gS4p1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP3gS4p1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP3gS4p1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP3gS4p1\App_KernelDevDebugContainer([
    'container.build_hash' => 'P3gS4p1',
    'container.build_id' => 'f9761288',
    'container.build_time' => 1744927610,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP3gS4p1');
