<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHbJqHfo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHbJqHfo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHbJqHfo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHbJqHfo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHbJqHfo\App_KernelDevDebugContainer([
    'container.build_hash' => 'HbJqHfo',
    'container.build_id' => '010b3452',
    'container.build_time' => 1744329226,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHbJqHfo');
