<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqjFE7f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqjFE7f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqjFE7f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqjFE7f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXqjFE7f\App_KernelDevDebugContainer([
    'container.build_hash' => 'XqjFE7f',
    'container.build_id' => '6a78e661',
    'container.build_time' => 1745843377,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqjFE7f');
