<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'ajout_event' => [[], ['_controller' => 'App\\Controller\\CategorieEventController::ajouterCategorie'], [], [['text', '/ajouter-evenement']], [], [], []],
    'liste_categories' => [[], ['_controller' => 'App\\Controller\\CategorieEventController::listeCategories'], [], [['text', '/liste-categories']], [], [], []],
    'supprimer_categorie' => [['id'], ['_controller' => 'App\\Controller\\CategorieEventController::supprimerCategorie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/supprimer-categorie']], [], [], []],
    'modifier_categorie' => [['id'], ['_controller' => 'App\\Controller\\CategorieEventController::modifierCategorie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifier-categorie']], [], [], []],
    'app_event_index' => [[], ['_controller' => 'App\\Controller\\EventController::index'], [], [['text', '/event']], [], [], []],
    'app_event_new' => [[], ['_controller' => 'App\\Controller\\EventController::new'], [], [['text', '/event/new']], [], [], []],
    'app_event_show' => [['id'], ['_controller' => 'App\\Controller\\EventController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/event']], [], [], []],
    'app_event_edit' => [['id'], ['_controller' => 'App\\Controller\\EventController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/event/event']], [], [], []],
    'app_event_delete' => [['id'], ['_controller' => 'App\\Controller\\EventController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/event']], [], [], []],
    'app_event_public' => [[], ['_controller' => 'App\\Controller\\EventController::list'], [], [['text', '/event/event/showclient']], [], [], []],
    'event_show' => [['id'], ['_controller' => 'App\\Controller\\EventController::showevent'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/event/event/showEvent']], [], [], []],
    'app_home_controll' => [[], ['_controller' => 'App\\Controller\\HomeControllController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\CategorieEventController::ajouterCategorie' => [[], ['_controller' => 'App\\Controller\\CategorieEventController::ajouterCategorie'], [], [['text', '/ajouter-evenement']], [], [], []],
    'App\Controller\CategorieEventController::listeCategories' => [[], ['_controller' => 'App\\Controller\\CategorieEventController::listeCategories'], [], [['text', '/liste-categories']], [], [], []],
    'App\Controller\CategorieEventController::supprimerCategorie' => [['id'], ['_controller' => 'App\\Controller\\CategorieEventController::supprimerCategorie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/supprimer-categorie']], [], [], []],
    'App\Controller\CategorieEventController::modifierCategorie' => [['id'], ['_controller' => 'App\\Controller\\CategorieEventController::modifierCategorie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifier-categorie']], [], [], []],
    'App\Controller\EventController::index' => [[], ['_controller' => 'App\\Controller\\EventController::index'], [], [['text', '/event']], [], [], []],
    'App\Controller\EventController::new' => [[], ['_controller' => 'App\\Controller\\EventController::new'], [], [['text', '/event/new']], [], [], []],
    'App\Controller\EventController::show' => [['id'], ['_controller' => 'App\\Controller\\EventController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/event']], [], [], []],
    'App\Controller\EventController::edit' => [['id'], ['_controller' => 'App\\Controller\\EventController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/event/event']], [], [], []],
    'App\Controller\EventController::delete' => [['id'], ['_controller' => 'App\\Controller\\EventController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/event']], [], [], []],
    'App\Controller\EventController::list' => [[], ['_controller' => 'App\\Controller\\EventController::list'], [], [['text', '/event/event/showclient']], [], [], []],
    'App\Controller\EventController::showevent' => [['id'], ['_controller' => 'App\\Controller\\EventController::showevent'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/event/event/showEvent']], [], [], []],
    'App\Controller\HomeControllController::index' => [[], ['_controller' => 'App\\Controller\\HomeControllController::index'], [], [['text', '/']], [], [], []],
];
